### ISSUE TITLE
Ambiguity Error

### ISSUE THREAD

**Issue by EsTharian** [taw10/crystfel#4] opened 2021-12-05 13:45 UTC
I was working with SLAC/mfxp17318_0015 data. After all indexing with determined unit cell file, I got `Subprocess exited with status 512` error with no message while running `Indexing Ambiguity` worker.

I couldn't debug it yet for the reason of error, but, there should be a log of exception.

Is there any known possible reason of the error?

**Comment by taw10** [comment] 2021-12-06 10:47
Take a look in the folder corresponding to the ambiguity run - it will be in the directory where you run the GUI, and its name will be the same as the title you gave to your job.  In there, you should find more information about what went wrong.  Look in stderr.log and stdout.log in particular.  Maybe the problem is obvious from that.   If not, paste the contents of stderr.log here and I'll investigate further.

**Comment by EsTharian** [comment] 2021-12-06 15:37
![image](https://user-images.githubusercontent.com/25347659/144874653-5a5796e7-8b48-4cc4-85da-ec414aa067e2.png)

Unfortunately, there isn't any log. It may be required to debug using GDB. I may investigate it if you wish.

**Comment by taw10** [comment] 2021-12-08 10:18
I'm not sure GDB will be much help in this situation, but feel free to try if you can.  The call to create the subprocess is succeeding, and the first part of the job script is succeeding (it creates ambigator-input.stream), but ambigator itself doesn't seem to be starting up.

Could you please post the contents of `run-ambigator.sh`?  Perhaps the contents already show an obvious error.  Otherwise, try running the run-ambigator.sh script manually.  Note that this needs to be done from the same folder as where the GUI is run (i.e. from the parent directory of `five-ambi` in your case), i.e. run `sh five-ambi/run-ambigator.sh`.

**Comment by taw10** [comment] 2022-06-07 14:18
I'm closing this because 6 months have passed without any comments.  If you're still having this problem, please re-open (here or on DESY Gitlab, at your option) with the requested information.

**Closed by taw10** 2022-06-07 14:18 UTC
